print ("inserta tu año de nacimiento")
añoN = int (input ())
print ("inserta tu mes de nacimiento EJEMPLO Enero 01 Febrero 02 ETC")
print ("recuerda no tilizar numeros mallores a 12")
mesN = int (input ())
print ("inserta el año actual")
añoA = int (input ())
print ("inserta mes actual en formato numerico. EJEMPLO Enero = 01 Febrero = 02 ETC")
print ("recuerda no tilizar numeros mallores a 12")
mesA = int (input ())
edad = str (añoA - añoN)
Meses = str (mesA - mesN)

print (" tu edad es " + edad + " años con " + Meses + " meses")
